[project]
name = "catalogit-backend"
version = "1.1.1"
description = "CatalogIT API backend"
license = { text = "MIT" }
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlalchemy[asyncio]",
    "asyncpg",
    "alembic",
    "pydantic-settings",
    "python-jose[cryptography]",
    "httpx",
    "python-multipart",
    "bcrypt",
    "aiobotocore",
    "cryptography",
]

[tool.hatch.build.targets.wheel]
packages = ["app"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
